export const STONES = [
    { id: 'fehu', symbol: 'ᚠ', name: 'Fehu', meaning: 'Wealth', essence: 'Abundance, success, and earned income.', merkstave: 'Greed, financial loss, or atrophy.' },
    { id: 'uruz', symbol: 'ᚢ', name: 'Uruz', meaning: 'Ox', essence: 'Physical strength, speed, and untamed potential.', merkstave: 'Weakness, misdirected force, or sickness.' },
    { id: 'thurisaz', symbol: 'ᚦ', name: 'Thurisaz', meaning: 'Thorn', essence: 'Reactive force, protection, and conflict.', merkstave: 'Defenselessness, betrayal, or compulsion.' },
    { id: 'ansuz', symbol: 'ᚨ', name: 'Ansuz', meaning: 'God', essence: 'Communication, divine inspiration, and wisdom.', merkstave: 'Misunderstanding, delusion, or vanity.' },
    { id: 'raidho', symbol: 'ᚱ', name: 'Raidho', meaning: 'Chariot', essence: 'Travel, rhythm, evolution, and the journey.', merkstave: 'Stagnation, injustice, or irrationality.' },
    { id: 'kenaz', symbol: 'ᚲ', name: 'Kenaz', meaning: 'Torch', essence: 'Vision, creativity, and transformation.', merkstave: 'Lack of creativity, breakup, or exposure.' },
    { id: 'gebo', symbol: 'ᚷ', name: 'Gebo', meaning: 'Gift', essence: 'Balance, partnership, and generosity.', merkstave: null },
    { id: 'wunjo', symbol: 'ᚹ', name: 'Wunjo', meaning: 'Joy', essence: 'Harmony, prosperity, and spiritual fruit.', merkstave: 'Striving, alienation, or sorrow.' },
    { id: 'hagalaz', symbol: 'ᚼ', name: 'Hagalaz', meaning: 'Hail', essence: 'Destruction, natural forces, and testing.', merkstave: null },
    { id: 'nauthiz', symbol: 'ᚾ', name: 'Nauthiz', meaning: 'Need', essence: 'Necessity, restriction, and endurance.', merkstave: 'Deprivation, drudgery, or hunger.' },
    { id: 'isa', symbol: 'ᛁ', name: 'Isa', meaning: 'Ice', essence: 'Stasis, stillness, and psychological blocks.', merkstave: null },
    { id: 'jera', symbol: 'ᛃ', name: 'Jera', meaning: 'Year', essence: 'Harvest, natural cycles, and patience.', merkstave: null },
    { id: 'eihwaz', symbol: 'ᛇ', name: 'Eihwaz', meaning: 'Yew', essence: 'Continuity, endurance, and protection.', merkstave: null },
    { id: 'perthro', symbol: 'ᛈ', name: 'Perthro', meaning: 'Lot Cup', essence: 'Fate, mystery, and occult knowledge.', merkstave: 'Addiction, stagnation, or loneliness.' },
    { id: 'algiz', symbol: 'ᛉ', name: 'Algiz', meaning: 'Elk', essence: 'Higher self, protection, and sanctuary.', merkstave: 'Hidden danger or vulnerability.' },
    { id: 'sowilo', symbol: 'ᛊ', name: 'Sowilo', meaning: 'Sun', essence: 'Success, wholeness, power, and healing.', merkstave: null },
    { id: 'tiwaz', symbol: 'ᛏ', name: 'Tiwaz', meaning: 'Tyr', essence: 'Honor, justice, and leadership.', merkstave: 'Over-analysis or lack of passion.' },
    { id: 'berkano', symbol: 'ᛒ', name: 'Berkano', meaning: 'Birch', essence: 'Growth, fertility, and new beginnings.', merkstave: 'Stagnation, domestic trouble, or anxiety.' },
    { id: 'ehwaz', symbol: 'ᛖ', name: 'Ehwaz', meaning: 'Horse', essence: 'Trust, teamwork, and loyalty.', merkstave: 'Restlessness, betrayal, or disharmony.' },
    { id: 'mannaz', symbol: 'ᛗ', name: 'Mannaz', meaning: 'Human', essence: 'The self, community, and shared identity.', merkstave: 'Isolation, manipulation, or self-delusion.' },
    { id: 'laguz', symbol: 'ᛚ', name: 'Laguz', meaning: 'Water', essence: 'Intuition, flow, and the subconscious.', merkstave: 'Emotional drowning or fear.' },
    { id: 'ingwaz', symbol: 'ᛝ', name: 'Ingwaz', meaning: 'Seed', essence: 'Internal growth and gestation.', merkstave: null },
    { id: 'dagaz', symbol: 'ᛞ', name: 'Dagaz', meaning: 'Day', essence: 'Breakthrough, clarity, and transformation.', merkstave: null },
    { id: 'othala', symbol: 'ᛟ', name: 'Othala', meaning: 'Heritage', essence: 'Ancestry, home, and inherited wealth.', merkstave: 'Homelessness or bad karma.' },
    { id: 'wyrd', symbol: ' ', name: 'Wyrd', meaning: 'The Void', essence: 'The unknowable and karmic fate.', merkstave: null }
  ];